apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gepp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-alkl-tenant/rhtap-demo-app/hacbs-test-project-gepp@sha256:05f1d2e7628a3642213c547975c27cc34b9c46e3186ed7922a56e4c827c692e5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
